version: "3"

services:
  web:
    build: .
    environment:
      - DATABASE_URL=ecto://postgres:postgres@postgres/koyeb_docker_compose_test_prod
      - SECRET_KEY_BASE=123abc123
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  postgres:
    image: postgres:15.12-alpine
    container_name: "postgres"
    ports:
      - "5432:5432"
